sudo: required

services:
  - docker

branches:
  only:
    - /^v[\d\.]+$/

env:
  global:
    - secure: "qSpfPHin4zS9yi4alWJGVHIO/4W5NYDxE4sW1uOJRIzOdgnEQw8BGrTUyUEwdBeM1xSGk5l+MJN0OJSyq0149YGT1vUIUIQJ1jIokas6R2ns9U4+EqU3IqVE61ZWH919pHgeSbgbZXvr1eovg60bhHcugUTRqNQi/tDKD7oi/qsIEQMoRdQFCMOCZyucaf+kjvq2e9soge/LPl3sbjQhNuh0fKLDn4VWbcR3/zOItfAoUBR44khVJwCmQk1dr9O1hnOkr1OLcrRN3nyzhQQCQjIlxbsy2P+XP5f+E2ncn9bqZ8BvyRLX1Xkpy97+yt7T8mtQlD2vwf1zHIJuYESwWAiNaKYEgvA43TC2bR1Ld48Ti58MCqjCgUeY9QNolVlm+ZoU6TvWYzEDKVkmqPFdTBoRRUECcdvBxHelxMrGOOs8b+ctqRWunXPfMh8IXPKu6866FYbPjljhEX3KUoMFaYvVdoJJCpWB7VzWeIFYgWugexpFcsacJRhv3n+Uf63pMiYEY8cnbVRYsFa3FBrs74hCFx2pvmnYRw2IHqAx9ow0TAso8Ee0486qBF58yAmO7D+rTIgwuIkzOea32UYMYY/RPIpHm9iF4peNDq2GHJtWxIdBEJUw3e/WUCDg2HnDDf3q/Z1Bu/0BeVn/C2EPSyc2FNMkLl1+SDmDf1iEHYs="
    - secure: "EZF1Rhvcrmuiio32lBdJ/2G1HeVyhTafLAze4DUvo4WfMntKC/aC7S5XjMKxKsCsFxazOqPPoq+/n5BFK7r8TP8KxyKfIYJgLBcuFFVqiQ8JsgliFEtngEnfgk/x2IjjnuF6Il1DKIL8cLYkRa7eE8NShX8th2DTFnWs9Te2oxdCyuZLUPgduJiYk9X1dnEVNrCcgE0s9KSGT3EJAUY9cz34c5nmqvOclImYBEIFMk/uc9OBP1lWmuInr9DraYHurAUKE8pC0/dXoMNwF+0tnhAkiBpUZ1kgWyL4MSviFdciVfO3vVBVdOJ1/PpwXbISH6RWX4NpOqUhdgrLU332p0Y0HTlv/lxQXC//2kcBQwuuT8eMRX83f1NVSOGE/+eOc5DAzM+FBzqLLj/K8/hqS9L0kBj+5rNoqsn4CHmKVmMgtK6kweLuJQa3VARDrCqSeJs16GZ5ftDjp0q92f6+Dq/a80foGrb6lkue/Ot0phnNVc/5tzABMoDM+wIPVk6iTjxEgvtpWj07rQUjh2FUo2M5Bq1sT5vsyxcsRiYLXbApf3nM3eps9BPLjJu62byG82UHScapmTb3plv56oNyuhPJLl4BpfQ3vSDMqre8CXhk6uDxITaI1QSHok2WbdlHXTl3RCYAETYAMMI8SisNOy/v9fe6POPNg311CET4x1g="

script:
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - make release
  - docker logout
